### ISSUE TITLE
TV field

### ISSUE THREAD

**Issue by kevinburke** [mdahlman/nba-schedule#12]
Thank you for posting this, it's very valuable. I noticed the TV field was empty. Are you planning to populate it? Is there a way to predict which games are the TV games based on times?

**Comment by mdahlman** [comment]
Thanks! Predicting games based on day of week and time would probably have a reasonably high success rate. There's certainly a good correlation... but it would be far from perfect.

The TV field is somewhat historical--I had populated it in past years. But I gathered the data in different ways in different years. This year I didn't get it, so the metadata remained but there's no data.
But adding it probably wouldn't be too hard. I'll try to take a look at it this weekend.

**Comment by mdahlman** [comment]
With 32 hours or so before the first game tips off, I have added TV, LOCAL_TV, and RADIO.
